alphabetworkers/alphabetworkersunion.org

- CONTRIBUTING.md
- frontend/README.md
* Removes instances of old repo name
* Correct contact address, repo, Google patching policy, and license links
* Contributions are open to all
> Updates to contributing for current repo name

- frontend/src/element/signup.ts
- signup-worker/src/handler.ts
Started working on the styling, added more fields that I know are essential.
> Signup worker more fields

- CONTRIBUTING.md
This closes out the commitments laid out by the publish proposal.
https://www.dropbox.com/scl/fi/07q5987jj9hfc6d064mtz/Proposal-to-Publish-Source-Code.paper
> Added instructions for contributing anonymously

- frontend/content/power/events.en.md
Also remove the February 27 event, since two events in a weekend is plenty.
> Add February 28 info session events

- frontend/src/element/signup.scss
- frontend/src/element/signup.ts
> Added an optional hourly-rate-to-annual-TC calculator

- frontend/src/element/signup.scss
- frontend/src/element/signup.ts
- signup-worker/src/handler.ts
> TC calculator, mailing/team/building fields

- frontend/content/power/faq.en.md
AWU->AWU-CWA
Removed references to strike fund
Added blub about dropthedeadnames
> Minor updates to the FAQ

- frontend/content/power/faq.en.md
The interest form link is also no longer specific to managers, so I removed that word.
> Be clearer that managers can join

- frontend/src/element/signup.scss
- frontend/src/element/signup.ts
- signup-worker/src/fields.ts
- signup-worker/src/handler.ts
- All payment options into a single section
- Fix some screwiness with hover states
- Pass through card processing fees when people opt to sign up w a card
- Add birthday and sms consent to join form
> Revisions to signup form

- frontend/content/power/faq.en.md
Please let me know if some other wording would be preferred! Happy to change it.
> Request to add info submitting the AWU Card Sign form with a Canadian Address

- signup-worker/src/global.d.ts
- signup-worker/src/handler.ts
- signup-worker/src/sendgrid.ts
Uses the sendgrid API to send a confirmation email after setting everything up in Stripe for the card sign.
> Send confirmation email on join

- frontend/config/prod/params.toml
- signup-worker/src/handler.ts
- signup-worker/src/stripe.ts
per memcom request - initiation fee should be charged as soon as employment verification is complete.
> Split initiation charge onto separate invoice

- membership-sync-worker/index.mjs
- membership-sync-worker/package.json
- membership-sync-worker/wrangler.toml
> membership-sync-worker

- frontend/src/element/signup.ts
Addresses https://github.com/alphabetworkers/alphabetworkersunion.org/issues/148
> Change the collection explanation for phone #s

- signup-worker/.vars.dev
- signup-worker/wrangler.toml
Hmm, got rabbit-hole'd about the best way to do this - maybe the prod vars just need to be completely filled in but we can leave the test vars present on line 8?
> Hardcode configs into wrangler.toml

- common/constants.ts
- frontend/src/element/signup.ts
- signup-worker/src/handler.ts
- Move initiation fee to a const
- Error on $0/month dues
> Move initiation fee to const, error on $0 dues

- signup-worker/wrangler.toml
The fix for cad/usd requires this in the environment variables
> Add initiation fee product id

- frontend/src/element/signup.ts
- signup-worker/src/handler.ts
Before (left) and after's of the UI change
> Clarify comp box, set threshold for maybe incorrect input

- frontend/content/power/busting-myths.en.md
- frontend/content/principles/articles-full.en.md
- frontend/content/principles/articles.en.md
Also make a first pass at updating the easy version of the articles to match.
> Update the Articles 

- frontend/src/element/signup.ts
This finishes addressing https://github.com/alphabetworkers/alphabetworkersunion.org/issues/148
> Tweak wording around terms for SMS updates.

- .envrc
- .gitignore
- flake.lock
- flake.nix
- join-form-js/package-lock.json
- join-form-js/src/signup.ts
A secondary error was caused by incorrectly trying to handle a different error.  This will resolve that secondary error, revealing the primary error to the user.
> Gracefully handle the failure to find error field

- join-form-js/src/signup.ts
- signup-worker/src/fields.ts
Adds a discord username field to the join form
> feat: start asking for discord usernames in signup.ts
